/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package OHOS.CameraStandard;
import CameraTypes;
sequenceable CameraMetadataInfo..OHOS.Camera.CameraMetadata;

interface IMechSessionCallback{
    [ipccode 0, oneway] void OnFocusTrackingInfo([in] int streamId, [in] boolean isNeedMirror, [in] boolean isNeedFlip, [in] sharedptr<CameraMetadata> results);
    [ipccode 1, oneway] void OnCaptureSessionConfiged([in] CaptureSessionInfo captureSessionInfo);
    [ipccode 2, oneway] void OnZoomInfoChange([in] int sessionid, [in] ZoomInfo zoomInfo);
    [ipccode 3, oneway] void OnSessionStatusChange([in] int sessionid, [in] boolean status);
}
